---
- hosts: webservers
  become: yes
  tasks:
    - name: apache installing
      package:
        name: apache2
        state: present
    - name: copy built files to deploy-server
      copy:
        src: /var/lib/jenkins/workspace/angular_test/dist/angular-hello-world/
        dest: /var/www/html/

    - name: restart apache
      systemd:
        name: apache2
        state: restarted
