---
- hosts: node-server
  become: yes
  tasks:
    - name: copy built files to deploy-server
      synchronize:
        src: /var/lib/jenkins/workspace/angular-app/dist/angular-hello-world/
        dest: /var/www/html/
        delete: true
        recursive: true

    - name: restart apache
      systemd:
        name: apache2
        state: restarted
