version: 0.2
env:
  variables:
    S3_BUCKET: "angulartest12345"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      #- npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build 
      #- ng build --configuration production --aot
  post_build:
     commands:
      - aws s3 sync dist/angular-hello-world/ s3://${S3_BUCKET}
      - echo "Build completed on `date`"
      - aws s3 website s3://${S3_BUCKET} --index-document index.html 
      - aws cloudfront create-invalidation --distribution-id E1OQ3NP8XCRA0J --paths '/*'
     

artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
